### ISSUE TITLE
world dominance

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/tw#14]
> Dominance is calculated as the percentage of player-owned villages belonging to a tribe. For example, if there are 100,000 player-owned villages in a world, and a tribe owns 50,000 of those villages, that tribe has 50% dominance.
> Requirements to win
> 
> For a tribe to win the world, both of the following conditions must be met (precise requirements depend on world settings):
> - The world must be of a minimum age
> - The tribe must meet the required level of dominance

– https://help.tribalwars.net/wiki/World_ending#Dominance

**Comment by Durdel** [comment]
In contrast to a simple domination, using Secrets of Power could ensure interesting fights among the best tribes while allowing smaller players to still have fun at the end.

**Comment by derhuerst** [comment]
> A tribe that manages to hold a full set of Secrets for a certain time will be the dominant force in this new age and will win the game.
> 
> You gain control of a secret when you conquer the village where it is currently stored or the secret is moved into one of your villages. Unlike troops, a secret can only move a small number of fields at a time. After being moved, the secret needs to rest in the village for a set amount of time, dependent on world settings. Once you give a move order to a secret, it will leave your control - you cannot cancel the move or get it back (unless it is moved back to you), […].
> 
> After a while, secrets will start to spread around a tribe holding them. You will receive periodic updates informing you when and possibly to where the secret will spread. […] Eventually the secrets will spread around more and more, making it ever harder to keep your opponents' greedy hands from them. Eventually it will be time to make an attack on any villages holding secrets your tribe does not yet control.
> Winning the game
> 
> To win the game a tribe must hold a full set of secrets. […] your tribe must have at least one instance of each named secret. After a tribe has acquired control of a full set, a victory countdown timer will start. If a tribe retains control of a whole set for the countdown period, it will win the game.

– https://help.tribalwars.net/wiki/World_ending#Secrets_of_Power
